---
version: "3.9"

services:
  backuppc:
    image: tiredofit/backuppc:6.0.1
    environment:
      - BACKUPPC_UUID=$app_puid
      - BACKUPPC_GUID=$app_pgid

        #- NGINX_AUTHENTICATION_TYPE=BASIC
        #- NGINX_AUTHENTICATION_BASIC_USER1=backuppc
        #- NGINX_AUTHENTICATION_BASIC_PASS1=backuppc
        #- DEBUG_MODE=FALSE # Start script of tiredofit
      - TZ=$app_tz
    working_dir: /data/
    volumes:
      - $app_dir_conf/etc:/etc/backuppc
        # - $app_dir_conf/home:/home/backuppc/ # is also valid
      - $app_dir_conf/ssh:/home/backuppc/.ssh/
      - $app_dir_data:/var/lib/backuppc
      - $app_dir_logs:/www/logs

