version: "3.7"
services:
  netbox:
    image: ${app_image:-${app_image_name}:${app_image_version}}
    environment:
      - PUID=$app_puid
      - PGID=$app_pgid
      - TZ=$app_tz
      - SUPERUSER_EMAIL=${app_admin_email}
      - SUPERUSER_PASSWORD=${app_admin_pass}
      - ALLOWED_HOST=${app_fqdn}
      - DB_NAME=${app_db_name}
      - DB_USER=${app_db_user}
      - DB_PASSWORD=${app_db_pass}
      - DB_HOST=netbox-db
      - DB_PORT=5432
      - REDIS_HOST=netbox-redis
      - REDIS_PORT=6379
      #- REDIS_PASSWORD=<REDIS_PASSWORD>
      - REDIS_DB_TASK=0 # Database ID for tasks
      - REDIS_DB_CACHE=1 # Database ID for cache
      #- BASE_PATH=<BASE_PATH> #optional
      #- REMOTE_AUTH_ENABLED=<REMOTE_AUTH_ENABLED> #optional
      #- REMOTE_AUTH_BACKEND=<REMOTE_AUTH_BACKEND> #optional
      #- REMOTE_AUTH_HEADER=<REMOTE_AUTH_HEADER> #optional
      #- REMOTE_AUTH_AUTO_CREATE_USER=<REMOTE_AUTH_AUTO_CREATE_USER> #optional
      #- REMOTE_AUTH_DEFAULT_GROUPS=<REMOTE_AUTH_DEFAULT_GROUPS> #optional
      #- REMOTE_AUTH_DEFAULT_PERMISSIONS=<REMOTE_AUTH_DEFAULT_PERMISSIONS> #optional
    volumes:
      #- ./netbox_config:/config
      - $app_dir_conf:/etc/netbox/config
      - $app_dir_template/scripts:/etc/netbox/scripts:z,ro
      
      - $app_conf/reports:/etc/netbox/reports
      - $app_dir_media:/opt/netbox/netbox/media:z
        #ports:
        #  - 13031:8000
    depends_on:
      - netbox-db
      - netbox-redis
    restart: unless-stopped

  netbox-db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - $app_dir_root/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${app_db_pass}
      - POSTGRES_DB=${app_db_name}
      - POSTGRES_USER=${app_db_user}
  netbox-redis:
    image: redis:7-alpine
    user: 1000:1000
    command: redis-server
    restart: always
    volumes:
      - $app_dir_root/redis_data:/data

