
services:
  authentik-proxy:
    image: ghcr.io/goauthentik/proxy
    restart: unless-stopped
      #ports:
      #    - 4180:4180
      #    - 4443:4443
      #    # Starting in authentik 2021.9, use the ports below
      #    # - 9000:9000
      #    # - 9443:9443
    environment:
        AUTHENTIK_HOST: $authentik_host
        AUTHENTIK_INSECURE: $authentik_insecure
        AUTHENTIK_TOKEN: $authentik_token
        # Starting with 2021.9, you can optionally set this too
        # when authentik_host for internal communication doesn't match the public URL
        AUTHENTIK_HOST_BROWSER: $authentik_host_browser

    labels:
      - traefik.enable=true
      - traefik.group=${traefik_svc_group:-}
      - "traefik.http.middlewares.${traefik_middleware_name:-authentik}.forwardAuth.address=${app_prot}://${app_name}:${app_port}/outpost.goauthentik.io/auth/traefik"
      - 'traefik.http.middlewares.${traefik_middleware_name:-authentik}.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.${traefik_middleware_name:-authentik}.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version'

