version: "3.7"

services:

  lum:
    image: ${app_image_name:-wheelybird/ldap-user-manager}:${app_image_version:-v1.9}
    restart: unless-stopped
    environment:
      - "SERVER_HOSTNAME=$app_fqdn"
      - "SERVER_PORT=${traefik_svc_port:-80}"

      - "ORGANISATION_NAME=${ldap_org:-LDAP}"
        #- "SITE_NAME=${ldap_domain:-$app_domain} ${app_description:-user manager}"
      - "SITE_NAME=${app_description:-${ldap_domain:-$app_domain}}"


        #- "LDAP_URI=$ldap_uri"
      - "LDAP_URI=${ldap_prot}://${ldap_host}"
      - "LDAP_BASE_DN=$ldap_base_dn"
      - "LDAP_ADMINS_GROUP=admins"
      - "LDAP_ADMIN_BIND_DN=$ldap_admin_bind_dn"
      - "LDAP_ADMIN_BIND_PWD=$ldap_admin_bind_pass"
      - "LDAP_IGNORE_CERT_ERRORS=true"
      - "NO_HTTPS=true" # Tofix, we can't use: ldap_tls here ...

