version: "3.9"

services:
    ui:
        image: joxit/docker-registry-ui:latest
        restart: always
        environment:
            - DELETE_IMAGES=true
            - REGISTRY_TITLE=$app_fqdn
            - NGINX_PROXY_PASS_URL=http://registry:5000
            - SINGLE_REGISTRY=true

