
# See: https://www.reddit.com/r/unRAID/comments/pbic8g/how_to_add_environment_variables_to_authelia/

networks:
  default:

version: "3.7"
services:
  authelia:
    image: ${app_image_name:-authelia/authelia}:${app_image_version:-4.36}
    command:
      - authelia
      - "--config=/config/configuration.yml"
      - "--config=/config/configuration.file.yml"
      - "--config=/config/configuration.local.yml"

    volumes:
      - $app_dir_conf:/config
    labels:
      - 'traefik.http.middlewares.${traefik_svc_auth:-authelia}.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.${traefik_svc_auth:-authelia}.forwardauth.address=http://${app_alias:-authelia}:9091/api/verify?rd=https://${app_fqdn}'
      - 'traefik.http.middlewares.${traefik_svc_auth:-authelia}.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
    healthcheck:
      disable: true
    networks:
      default:
        aliases:
          - ${app_alias:-authelia}
    environment:

      # MISC
      - AUTHELIA_DEFAULT_REDIRECTION_URL=${app_prot}://${app_fqdn}
      - AUTHELIA_SESSION_DOMAIN=${app_domain}
      #- AUTHELIA_AUTHENTIFICATION_BACKEND_PASSWORD_RESET_CUSTOM_URL=https://users.auth.${app_domain}

      # Direct password insertion
      - AUTHELIA_JWT_SECRET=$authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET=$authelia_session_secret
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=$authelia_storage_encryption_key

      # Secret management (TODO)
      # - AUTHELIA_JWT_SECRET_FILE=/config/secret_jwt
      # - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/secret_storage
      # - AUTHELIA_SESSION_SECRET_FILE=/config/secret_session
      # - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/config/secret_ldap
      # - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/config/secret_mysql
      # - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/config/secret_postgresql
      # - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/config/secret_smtp
