version: '3.9'


services:
  gitea:
    image: "${app_image:-gitea/gitea}:${app_image_version:-1.16}"
    restart: unless-stopped
    environment:
      # https://docs.gitea.io/en-us/config-cheat-sheet/
      # https://docs.gitea.io/en-us/install-with-docker/#environments-variables
      - APP_NAME=$app_description
      - USER_UID=$app_puid
      - USER_GID=$app_pgid
      - RUN_MODE=prod

      - GITEA__server__PROTOCOL=http
      - GITEA__server__HTTP_PORT=$traefik_svc_port

      - GITEA__server__DOMAIN=$app_fqdn
      - GITEA__server__SSH_DOMAIN=$app_fqdn
      - GITEA__server__ROOT_URL=https://$app_fqdn
      # - GITEA__service__EMAIL_DOMAIN_WHITELIST=$app_domain
    labels:
      restic-compose-backup.volumes: true
      restic-compose-backup.volumes.include: "data_repos,data_ssh,data_var"

    volumes:
      - $app_dir_data/gitea:/data/gitea:rw
      - $app_dir_data/git:/data/git:rw
      - $app_dir_data/ssh:/data/ssh:rw

        #volumes:
        #  data_repos:
        #    driver: local
        #    driver_opts:
        #      type: none
        #      o: bind
        #      device: $app_dir_data/git
        #  data_ssh:
        #    driver: local
        #    driver_opts:
        #      type: none
        #      o: bind
        #      device: $app_dir_data/ssh
        #  data_var:
        #    driver: local
        #    driver_opts:
        #      type: none
        #      o: bind
        #      device: $app_dir_data/gitea
        #
