---

# See: traefik_svc_auth
#
services:
  server:
    labels:
      - "traefik.http.middlewares.${traefik_middleware_name:-authentik}.forwardAuth.address=http://authentik.auth:$app_port/outpost.goauthentik.io/auth/traefik"
        #- "traefik.http.middlewares.${traefik_middleware_name:-authentik}.forwardAuth.address=http://authentik.auth:$app_port/outpost.goauthentik.io/auth/${traefik_middleware_name:-authentik}"
      - 'traefik.http.middlewares.${traefik_middleware_name:-authentik}.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.${traefik_middleware_name:-authentik}.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version'

        #      # The referer thing ???
        #      - "traefik.http.middlewares.authentik-headers.headers.customresponseheaders.Access-Control-Allow-Methods=POST, GET, PUT, OPTIONS, DELETE"
        #      - "traefik.http.middlewares.authentik-headers.headers.customresponseheaders.Access-Control-Allow-Origin=*"
        #      - "traefik.http.middlewares.authentik-headers.headers.customresponseheaders.Access-Control-Allow-Headers=x-requested-with,Content-Type,Authorization"
        #

        #    labels:
        #      - 'traefik.http.middlewares.${traefik_middleware_name:-authelia}.forwardauth.trustForwardHeader=true'
        #      - 'traefik.http.middlewares.${traefik_middleware_name:-authelia}.forwardauth.address=http://${app_alias:-authelia}:9091/api/verify?rd=https://${app_fqdn}'
        #      - 'traefik.http.middlewares.${traefik_middleware_name:-authelia}.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  # yamllint disable-line rule:line-length
        #
