version: "3.7"

services:
  librespeed:
    image: ${app_image}:${app_image_version}
    environment:
      - PUID=$app_puid
      - PGID=$app_pgid
      - TZ=$app_tz
      - PASSWORD=$app_admin_pass
      - CUSTOM_RESULTS=false  #optional
      - DB_TYPE=sqlite #optional
    volumes:
      - $app_dir_conf:/config
