
# See for auto-unlock

version: "3.8"
services:
  vault:
    image: "${app_image_name:-vault}:${app_image_version:-1.12.0}"
    restart: unless-stopped
    environment:
      VAULT_ADDR: "http://0.0.0.0:${app_port:-8200}"
      VAULT_API_ADDR: "http://0.0.0.0:${app_port:-8200}"
        #VAULT_DEV_ROOT_TOKEN_ID: "${app_secret_token:-admin}"
      VAULT_LOG_LEVEL: debug
      VAULT_UI: 'true'
    command: vault server -config=/vault/config/config.hcl
    volumes:
      - $app_dir_logs/server:/vault/logs
      - $app_dir_conf/server:/vault/config
      - $app_dir_conf/server-policies:/vault/policies
      - $app_dir_share/server:/vault/plugins
      - $app_dir_share/data:/data
      - $app_dir_data/server:/vault/file


      # DEBUG
      - $app_dir_template/helpers:/helpers:rw
      - $app_dir_debug:/helpers/debug:rw
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
          - vault
          - vault.auth

