version: "3.9"

services:
  earthly:
    image: earthly/buildkitd:v0.7.19
    restart: always
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $app_dir_cache:/tmp/earthly
    ports:
      - $app_expose_ip:${app_expose_port:-8372}:8372
    environment:
      BUILDKIT_TCP_TRANSPORT_ENABLED: true
      BUILDKIT_TLS_ENABLED: false

