

version: '3'

services:
  pdns:
    #build: pdns
    image: pschiffe/pdns-mysql
    restart: unless-stopped
      #depends_on:
      #  - db
      #links:
      #  - "db:mysql"
      #ports:
      #  - "$app_expose_ip:53:53"
      #  - "$app_expose_ip:53:53/udp"
      #  - "$app_expose_ip:8081:8081"
    environment:
      - PDNS_master=yes 
      - PDNS_api=yes
      - PDNS_api_key=${app_token:-secret}
      - PDNSCONF_API_KEY=${app_token:-secret}
      - PDNS_webserver=yes 
      - PDNS_webserver-allow-from=0.0.0.0/0
        #- PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24 
      - PDNS_webserver_address=0.0.0.0 
        #- PDNS_webserver_password=secret2 
      - PDNS_version_string=anonymous 
      - PDNS_default_ttl=1500 
      - PDNS_allow_notify_from=0.0.0.0 
      - PDNS_allow_axfr_ips=127.0.0.1 
