
version: '3.9'

services:
  dnsmasq:
    image: jpillora/dnsmasq:latest
    restart: unless-stopped
    entrypoint: webproc --config /etc/dnsmasq.d/main.conf -- dnsmasq --no-daemon --conf-dir /etc/dnsmasq.d
    stop_grace_period: 2s
    volumes:
      - $app_dir_conf/:/etc/dnsmasq.d
    environment:
      HTTP_USER: $app_admin_user
      HTTP_PASS: $app_admin_pass
      # See doc: https://hub.docker.com/r/jpillora/dnsmasq

