
version: '3.9'

services:
  dnsmasq:
    image: jpillora/dnsmasq:latest
    volumes:
      - $app_dir_conf/dnsmasq.conf:/etc/dnsmasq.conf
    environment:
      HTTP_USER: $app_admin_user
      HTTP_PASS: $app_admin_pass
      # See doc: https://hub.docker.com/r/jpillora/dnsmasq

